version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: heroes-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: heroesdb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - rpg-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: heroes-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - rpg-network
      
volumes:
  postgres-data:
    
networks:
  rpg-network:
    driver: bridge